### ISSUE TITLE
Cannot run 'bakePreview' task when using gradle 7.4.2

### ISSUE THREAD

**Issue by jhrom** [jbake-org/jbake-gradle-plugin#68]
When I try to start bakePreview task, exception is thrown:

> Caused by: groovy.lang.MissingMethodException: No signature of method: 
org.gradle.internal.logging.services.DefaultLoggingManager.setLevel() is applicable for argument types: (org.gradle.api.logging.LogLevel) values: [INFO]
Possible solutions: getLevel()
        at org.jbake.gradle.JBakeServeTask.serve(JBakeServeTask.groovy:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

Other tasks work correctly

I'll submit fix for it soon

**Comment by jhrom** [comment]
[68-gradle-fix.patch.txt](https://github.com/jbake-org/jbake-gradle-plugin/files/9074784/68-gradle-fix.patch.txt)

Because of the lack of permissions, I was not able to create a new branch.  I attached the fix as a patch.

**Comment by tjuricek-at-salesforce** [comment]
This is not working with gradle 8.0 as well, the error just shows up a little differently.

```
Execution failed for task ':bakePreview'.
> Cannot set readonly property: level for class: org.gradle.internal.logging.services.DefaultLoggingManager
```

**Comment by mariogarcia** [comment]
Same here:

- Gradle 7.2
- JDK11

```
* What went wrong:
Execution failed for task ':website:bakePreview'.
> Cannot set readonly property: level for class: org.gradle.internal.logging.services.DefaultLoggingManager
```
